// One anchor space for the whole vault.
//
// A markdown heading and a LaTeX `\label` are the same kind of thing — a named
// place inside a note — so `[[Note#anchor]]` and `\ref{Note#anchor}` are one
// lookup, and neither the backlinks panel, the graph, the hover preview nor
// the outline has to know which format it is pointing at. Transclusion falls
// out of it for free: `![[Paper#eq:fourier]]` is "resolve the note, then
// resolve the anchor inside it", exactly as `![[Notes#Derivation]]` is.

import { isTexPath } from "./noteFormat.ts";
import { findAnchor, parseTex, slugAnchor, type NoteAnchor } from "./tex.ts";

export type { NoteAnchor } from "./tex.ts";
export { findAnchor, slugAnchor } from "./tex.ts";

const FENCE_RE = /^\s*(```|~~~)/;
const HEADING_RE = /^(#{1,6})\s+(.*)$/;

/** Inline markdown removed from a heading, for display and for slugging. Kept
 *  in step with client/reading/toc.ts's stripInline — that one feeds the TOC,
 *  this one feeds the anchor table, and an anchor whose id disagrees with the
 *  element id the reading view assigns is an anchor that silently misses. */
function stripInline(text: string): string {
  return text
    .replace(/!\[\[([^[\]]+?)\]\]/g, "$1")
    .replace(/\[\[([^\]|]+?)(?:\|([^\]]+))?\]\]/g, (_m, t: string, a?: string) => (a ?? t).trim())
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\*\*|__|~~|==/g, "")
    .replace(/(^|\s)[*_]|[*_](\s|$)/g, "$1$2")
    .replace(/\s+#+\s*$/, "")
    .trim();
}

/** Every addressable place in a markdown note: its headings. Slugs collide the
 *  same way the reading view's do (`intro`, `intro-1`, …), because they are
 *  generated by the same rule in the same document order. */
export function markdownAnchors(md: string): NoteAnchor[] {
  const out: NoteAnchor[] = [];
  const seen = new Map<string, number>();
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  let start = 0;
  if (lines[0]?.trim() === "---") {
    for (let j = 1; j < lines.length; j++) {
      const t = lines[j].trim();
      if (t === "---" || t === "...") {
        start = j + 1;
        break;
      }
    }
  }
  let inFence = false;
  for (let i = start; i < lines.length; i++) {
    const line = lines[i];
    if (FENCE_RE.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;
    const m = HEADING_RE.exec(line);
    if (!m) continue;
    const text = stripInline(m[2]);
    const base = slugAnchor(text);
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    out.push({ id: n === 0 ? base : `${base}-${n}`, kind: "heading", title: text, line: i + 1 });
  }
  return out;
}

/** The anchor table for a note of EITHER format — the one function every
 *  cross-format feature calls. `.tex` notes are parsed; markdown notes are
 *  scanned for headings. */
export function noteAnchors(relPath: string, content: string): NoteAnchor[] {
  if (!isTexPath(relPath)) return markdownAnchors(content);
  return parseTex(content).anchors;
}

/** Resolve `#anchor` inside a note's content, whatever the note's format.
 *  Returns null for a miss — every caller renders that quietly, never as an
 *  error and never as raw source. */
export function resolveAnchorIn(
  relPath: string,
  content: string,
  anchor: string,
): NoteAnchor | null {
  return findAnchor(noteAnchors(relPath, content), anchor);
}

/** The 1-based source line an `#anchor` sits on in a note of either format —
 *  what the editor scrolls to when a `[[Note#anchor]]` is followed. null when
 *  the anchor does not resolve, which every caller treats as "just open the
 *  note", never as an error. */
export function anchorLine(relPath: string, content: string, anchor: string): number | null {
  return findAnchor(noteAnchors(relPath, content), anchor)?.line ?? null;
}
