// The design config: what "designed" mode renders instead of the stock blog.
//
// ARCHITECTURE, and it is the non-negotiable part. The built-in blog is a
// PRISTINE, SEPARATE, ALWAYS-WORKING BASE. Nothing in this module, in
// server/designs.ts, or in client/design/ mutates, forks, subclasses,
// monkey-patches or re-styles a single stock blog component or a single rule
// in blog.css. `publicLayout` gains a third value and the client grows a
// SECOND renderer beside the first; the two never meet except at one `if`.
// A reviewer confirms that from the diff by checking that client/blog/* and
// client/styles/blog.css are untouched — they are.
//
// The consequence that makes the switch worth having: it is LOSSLESS BOTH
// WAYS. The design lives in its own file and is never consulted while
// `publicLayout` is anything but "designed", so flipping back to stock is a
// RESCUE (nothing is deleted, nothing is migrated, nothing is lost) and
// flipping forward again returns the site exactly as it was. That is also the
// one-click escape the error boundary offers an admin whose design is broken.
//
// This module is the SHAPE — types, the allowlist, per-key validation,
// migration and the stock defaults. It is shared because both sides need the
// same answer: the server validates on write, and the CLIENT validates again
// on read before it renders a byte, so a file that was hand-edited past the
// server (settings.json's own documented escape hatch, one directory up)
// still cannot put a malformed section in front of a visitor.

import { stripBidiControls } from "./bidi.ts";
// The CHROME — nav, typography, header, footer — is one field on this
// document. It lives in its own module because it is the half an author edits
// with builders rather than a section list, and because the same validator
// serves the server's write path and the client's re-check on read.
import {
  stockChrome,
  validateChrome,
  type DesignChrome,
} from "./designChrome.ts";
export type { DesignChrome } from "./designChrome.ts";

/** The schema THIS build authors and renders.
 *
 *  Migration is keyed off the schema a document declares, and there are
 *  exactly three outcomes, never a fourth:
 *    · equal to this      → rendered as-is (after validation)
 *    · older, with a step registered in MIGRATIONS → migrated, then validated
 *    · anything else (older with no step, or NEWER than this build) →
 *      QUARANTINED: kept on disk byte-for-byte, never rendered, and named in
 *      a message. A design authored by a newer Vellum must not be rendered
 *      "as best we can" — half-understood sections are precisely how a public
 *      site silently becomes wrong. */
export const DESIGN_SCHEMA = 1;

/** Where a design that names no schema is assumed to have come from. Not a
 *  hypothetical: export/import means designs will be hand-written and
 *  generated by other tools, and a missing `schema` is the commonest
 *  recoverable defect in either. It migrates (fill the defaults, adopt 1)
 *  rather than quarantining, because there is nothing here we could
 *  misunderstand — the fields we do not find, we supply. */
export const SCHEMA_UNVERSIONED = 0;

// ── Sections ────────────────────────────────────────────────────────────────

export type SectionKind =
  | "hero"
  | "richText"
  | "note"
  | "postGrid"
  | "postList"
  | "topics"
  | "cta"
  | "divider";

export const SECTION_KINDS: SectionKind[] = [
  "hero",
  "richText",
  "note",
  "postGrid",
  "postList",
  "topics",
  "cta",
  "divider",
];

interface SectionBase {
  /** Stable within a design. It is what the error boundary NAMES when this
   *  section is the one that threw, so it survives reordering and renaming. */
  id: string;
  kind: SectionKind;
  /** Kept in the config, skipped by the renderer. A hidden section is how an
   *  author tries something without losing it — the same "retained while
   *  inactive" rule the whole design file follows, one level down. */
  hidden?: boolean;
}

export interface HeroSection extends SectionBase {
  kind: "hero";
  /** Empty → the site name, so a hero costs no typing to be useful. */
  heading: string;
  sub: string;
  /** https URL or a vault-relative image path, exactly like `settings.logo`. */
  image: string | null;
  align: "start" | "center";
  height: "short" | "tall";
  /** WHAT SHAPE THE OPENING IS, which the first three fields could not say.
   *  `panel` is the rounded card the hero has always been. `band` is a field
   *  of ground and type running the full column with square corners — the
   *  opening for a site that has no photograph and does not want a generated
   *  one. `split` sets the words against the picture instead of on top of it,
   *  which is the arrangement a scrim cannot produce.
   *
   *  `cover` IS THE ONE THAT BREAKS THE COLUMN, and it is here because the
   *  stock blog's own dashboard has had it since before this engine existed: a
   *  photograph running the FULL WIDTH OF THE WINDOW with the site's name over
   *  it. Every other treatment lives inside `--dsn-width`, which meant the one
   *  opening a Vellum site most often already has was the one thing a design
   *  could not reproduce — an author who liked their front page could not start
   *  from it. It is the only section in the engine that leaves the column, it
   *  says so in its name, and `design.css` carries the full-bleed idiom (a
   *  negative logical margin against the page's own padding) in one place. */
  treatment: "panel" | "band" | "split" | "cover";
}

export interface RichTextSection extends SectionBase {
  kind: "richText";
  /** Rendered through the reading renderer — the same sanitizer, the same
   *  wikilink resolution, the same callouts. Authoring the public homepage in
   *  markdown is the point; inventing a second content format is not. */
  markdown: string;
  align: "start" | "center";
}

export interface NoteSection extends SectionBase {
  kind: "note";
  /** Vault-relative `.md` path. THE section that can point at a note the
   *  author later deletes or unpublishes — see the boundary. */
  note: string;
  heading: string;
  /** Show the first paragraph only, with a link through to the note. */
  excerpt: boolean;
}

export interface PostGridSection extends SectionBase {
  kind: "postGrid";
  heading: string;
  limit: number;
  columns: number;
  /** Restrict to one tag; empty = every published post. */
  tag: string;
  showExcerpt: boolean;
  showBanner: boolean;
  showDate: boolean;
  /** THE CARD'S ANATOMY, which was one shape for every design on the shelf.
   *  `boxed` is the bordered tile on raised ground. `bare` deletes the box and
   *  lets the picture and the words stand on the page. `overlay` puts the
   *  title on a scrim over the picture. `ledger` turns the tile on its side —
   *  thumbnail at the start, words at the end. `masonry` drops the grid for
   *  CSS columns so pictures keep their own proportions. */
  card: "boxed" | "bare" | "overlay" | "ledger" | "masonry";
}

export interface PostListSection extends SectionBase {
  kind: "postList";
  heading: string;
  limit: number;
  tag: string;
  showExcerpt: boolean;
  showDate: boolean;
  /** HOW THE RUN IS SET, and the reason every design on the shelf listed its
   *  writing the same way. `river` is the stacked title-meta-excerpt run this
   *  section shipped as. `ledger` rules every row and hangs the date in a
   *  column of its own. `index` is a table of contents — title, leader, date,
   *  nothing else. `numbered` counts the entries in oversized faint ordinals.
   *  `dateline` groups the run under the day it was published, the way a paper
   *  does. None of them decides a colour; all of them decide an arrangement. */
  layout: "river" | "ledger" | "index" | "numbered" | "dateline";
}

export interface TopicsSection extends SectionBase {
  kind: "topics";
  heading: string;
  limit: number;
}

export interface CtaSection extends SectionBase {
  kind: "cta";
  heading: string;
  body: string;
  label: string;
  /** Site-relative ("/topic/x") or an absolute https URL. Nothing else — a
   *  homepage button is not a place to accept `javascript:`. */
  url: string;
}

export interface DividerSection extends SectionBase {
  kind: "divider";
  /** `ornament` is the reading view's own `***` divider, drawn by the same
   *  idiom: an accent rule that fades at both ends with the wordmark's ✦ over
   *  a gap in the middle. A composed page breaks its run of sections for the
   *  same reason an essay breaks its run of paragraphs, and it should not have
   *  had to do it with a chrome hairline. */
  style: "rule" | "dots" | "ornament" | "blank";
  /** Vertical air, in px. */
  space: number;
}

export type Section =
  | HeroSection
  | RichTextSection
  | NoteSection
  | PostGridSection
  | PostListSection
  | TopicsSection
  | CtaSection
  | DividerSection;

// ── Site chrome + article page ──────────────────────────────────────────────

export interface DesignSite {
  /** The reading measure, px. Below the stock 720 for a tighter column, above
   *  it for a magazine. This governs the SECTION column; the article's own
   *  measure is `chrome.typography.measure`, in ch, because prose is measured
   *  in characters and a composed page is measured in pixels. */
  width: number;
  density: "compact" | "regular" | "roomy";
}

export interface DesignArticle {
  showBanner: boolean;
  showMeta: boolean;
  showTags: boolean;
  showRelated: boolean;
  showBackLink: boolean;
  /** An initial cap on the article's first paragraph. Off by default: it is a
   *  strong voice, not a refinement, and a site that did not ask for one must
   *  not grow one on upgrade. */
  dropCap: boolean;
}

export interface DesignDoc {
  id: string;
  name: string;
  /** The schema this document was authored against. Per-DOCUMENT rather than
   *  per-file: an imported design carries its own, and one stale import must
   *  not quarantine the designs beside it. */
  schema: number;
  /** A theme choice (built-in id or `custom:<slug>`) the designed site forces
   *  on visitors who have no stored preference, or null to leave
   *  `settings.defaultTheme` alone. A design is a look; a look is a theme plus
   *  a layout, and splitting them across two panels is how they drift. */
  theme: string | null;
  site: DesignSite;
  /** Nav, typography, header and footer — everything that frames the page
   *  rather than fills it (shared/designChrome.ts). */
  chrome: DesignChrome;
  sections: Section[];
  article: DesignArticle;
  createdMs: number;
  updatedMs: number;
}

/** What the admin list shows without fetching every document. */
export interface DesignSummary {
  id: string;
  name: string;
  schema: number;
  sections: number;
  updatedMs: number;
  /** Present when this document cannot be rendered by this build — the
   *  message names the reason, in the same voice the store logs it. */
  quarantine?: string;
}

// ── Limits ──────────────────────────────────────────────────────────────────

export const MAX_DESIGNS = 24;
export const MAX_SECTIONS = 40;
export const DESIGN_NAME_MAX = 60;
export const HEADING_MAX = 120;
export const SUB_MAX = 240;
export const MARKDOWN_MAX = 20_000;
export const URL_MAX = 500;
export const MIN_WIDTH = 520;
export const MAX_WIDTH = 1400;

// ── Stock defaults ──────────────────────────────────────────────────────────

/** "Reset to stock defaults" is always available, and this is what it means:
 *  a design that renders as close to the built-in blog as a composed tree can
 *  — masthead, topics nav, search, the list of writings — so an author who has
 *  painted themselves into a corner has a floor to stand on that is not the
 *  empty page. It is NOT the stock blog itself: the stock blog is reached by
 *  setting publicLayout back to "blog", which is a different, larger rescue
 *  and the one the error boundary offers. */
export function stockSite(): DesignSite {
  return { width: 720, density: "regular" };
}

export function stockArticle(): DesignArticle {
  return {
    showBanner: true,
    showMeta: true,
    showTags: true,
    showRelated: true,
    showBackLink: true,
    dropCap: false,
  };
}

export function stockSections(): Section[] {
  return [
    {
      id: "writings",
      kind: "postList",
      heading: "",
      limit: 20,
      tag: "",
      showExcerpt: true,
      showDate: true,
      // The floor is the stock blog's own shape, so it takes the layout that
      // has always drawn it. Everything else on the shelf is a choice.
      layout: "river",
    },
  ];
}

export function stockDesign(id: string, name: string, now = Date.now()): DesignDoc {
  return {
    id,
    name,
    schema: DESIGN_SCHEMA,
    theme: null,
    site: stockSite(),
    chrome: stockChrome(),
    sections: stockSections(),
    article: stockArticle(),
    createdMs: now,
    updatedMs: now,
  };
}

/** A blank section of `kind`, every key present at its default — the designer
 *  never has to invent a value, and validation never has to guess one. */
export function newSection(kind: SectionKind, id: string): Section {
  switch (kind) {
    case "hero":
      return {
        id,
        kind,
        heading: "",
        sub: "",
        image: null,
        align: "center",
        height: "short",
        treatment: "panel",
      };
    case "richText":
      return { id, kind, markdown: "", align: "start" };
    case "note":
      return { id, kind, note: "", heading: "", excerpt: false };
    case "postGrid":
      return {
        id,
        kind,
        heading: "",
        limit: 6,
        columns: 2,
        tag: "",
        showExcerpt: true,
        showBanner: true,
        showDate: true,
        card: "boxed",
      };
    case "postList":
      return {
        id,
        kind,
        heading: "",
        limit: 20,
        tag: "",
        showExcerpt: true,
        showDate: true,
        layout: "river",
      };
    case "topics":
      return { id, kind, heading: "", limit: 12 };
    case "cta":
      return { id, kind, heading: "", body: "", label: "", url: "/" };
    case "divider":
      return { id, kind, style: "rule", space: 32 };
  }
}

// ── Validation ──────────────────────────────────────────────────────────────

/** Every rejection this module makes. `path` names the offending place inside
 *  the document ("sections[2].limit"), which is what the admin notice prints
 *  and what makes a hand-edited file fixable without a debugger. */
export class DesignError extends Error {
  readonly path: string;
  constructor(path: string, message: string) {
    super(path ? `${path}: ${message}` : message);
    this.path = path;
  }
}

/** Thrown when a document cannot be understood by this build AT ALL and must
 *  be kept, not repaired. Separate from DesignError because the outcomes
 *  differ: a DesignError is a 400 on a write and a skipped row on a read; a
 *  QuarantineError is always a kept-but-inert row with a message. */
export class QuarantineError extends Error {}

function asObject(value: unknown, path: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new DesignError(path, "must be an object");
  }
  return value as Record<string, unknown>;
}

/** Single-line, control characters and bidi overrides stripped, capped.
 *  Bidi stripping is the `shared/bidi.ts` rule: this text is authored by the
 *  operator but it renders into the PUBLIC page beside note titles, and an
 *  RLO in a heading reorders everything after it. */
function text(value: unknown, path: string, max: number, fallback = ""): string {
  if (value === undefined || value === null) return fallback;
  if (typeof value !== "string") throw new DesignError(path, "must be a string");
  const clean = stripBidiControls(value).replace(/[\u0000-\u001f\u007f]+/g, " ").trim();
  if (clean.length > max) throw new DesignError(path, `is too long (${max} characters max)`);
  return clean;
}

/** Multi-line: newlines survive, control characters and bidi overrides do
 *  not. The one field this is for is a section's markdown body. */
function block(value: unknown, path: string, max: number): string {
  if (value === undefined || value === null) return "";
  if (typeof value !== "string") throw new DesignError(path, "must be a string");
  const clean = stripBidiControls(value).replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]+/g, "");
  if (clean.length > max) throw new DesignError(path, `is too long (${max} characters max)`);
  return clean;
}

function bool(value: unknown, path: string, fallback: boolean): boolean {
  if (value === undefined || value === null) return fallback;
  if (typeof value !== "boolean") throw new DesignError(path, "must be true or false");
  return value;
}

function int(value: unknown, path: string, min: number, max: number, fallback: number): number {
  if (value === undefined || value === null) return fallback;
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new DesignError(path, "must be a number");
  }
  const n = Math.round(value);
  if (n < min || n > max) throw new DesignError(path, `must be between ${min} and ${max}`);
  return n;
}

function oneOf<T extends string>(
  value: unknown,
  path: string,
  allowed: readonly T[],
  fallback: T,
): T {
  if (value === undefined || value === null) return fallback;
  if (typeof value !== "string" || !(allowed as readonly string[]).includes(value)) {
    throw new DesignError(path, `must be one of: ${allowed.join(", ")}`);
  }
  return value as T;
}

/** An image reference: an https URL or a vault-relative image path. The same
 *  rule `settings.logo` follows, and for the same reason — this lands in an
 *  `<img src>` on every visitor's homepage. `http:`, `data:` and `javascript:`
 *  are named rejections rather than falling through to path normalization,
 *  which would mangle a URL into a broken vault path and hide the mistake. */
const IMAGE_EXT = /\.(ico|png|svg|jpe?g|gif|webp|avif)$/i;
function imageRef(value: unknown, path: string): string | null {
  if (value === undefined || value === null || value === "") return null;
  const raw = text(value, path, URL_MAX);
  if (raw === "") return null;
  if (/^https:\/\//i.test(raw)) return raw;
  if (/^[a-z][a-z0-9+.-]*:/i.test(raw)) {
    throw new DesignError(path, "must be an https:// URL or a vault image path");
  }
  const rel = raw.replace(/\\/g, "/").replace(/^\/+/, "");
  if (rel === "" || rel.split("/").some((seg) => seg === "." || seg === "..")) {
    throw new DesignError(path, "is not a valid vault path");
  }
  if (!IMAGE_EXT.test(rel)) {
    throw new DesignError(path, "must be an image (ico, png, svg, jpeg, gif, webp, avif)");
  }
  return rel;
}

/** A link target: site-relative, or an absolute https URL. A homepage button
 *  is not a place that accepts `javascript:` — and "we sanitize it later" is
 *  how one eventually ships. */
function linkRef(value: unknown, path: string): string {
  const raw = text(value, path, URL_MAX, "/");
  if (raw === "") return "/";
  if (/^https:\/\//i.test(raw)) return raw;
  if (raw.startsWith("/") && !raw.startsWith("//")) return raw;
  throw new DesignError(path, "must be a site path starting with / or an https:// URL");
}

/** A vault-relative markdown path. */
function notePath(value: unknown, path: string): string {
  const raw = text(value, path, URL_MAX);
  if (raw === "") return "";
  const rel = raw.replace(/\\/g, "/").replace(/^\/+/, "");
  if (rel.split("/").some((seg) => seg === "." || seg === "..")) {
    throw new DesignError(path, "is not a valid vault path");
  }
  if (!/\.md$/i.test(rel)) throw new DesignError(path, "must be a markdown path (….md)");
  return rel;
}

const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;

export function slugifyDesignName(name: string): string {
  const slug = name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return slug === "" ? "design" : slug;
}

/** Validate one section. STRICT: an unknown `kind` and an unknown KEY are
 *  both errors naming the offender. Returns a fresh object carrying only
 *  allowlisted keys, so nothing unvalidated survives into the file. */
export function validateSection(input: unknown, path: string, index: number): Section {
  const raw = asObject(input, `${path}[${index}]`);
  const at = `${path}[${index}]`;
  const kind = raw.kind;
  if (typeof kind !== "string" || !SECTION_KINDS.includes(kind as SectionKind)) {
    throw new DesignError(`${at}.kind`, `must be one of: ${SECTION_KINDS.join(", ")}`);
  }
  const id = typeof raw.id === "string" && SLUG_RE.test(raw.id) ? raw.id : `s${index + 1}`;
  const hidden = bool(raw.hidden, `${at}.hidden`, false);

  const allowed = new Set(["id", "kind", "hidden", ...KIND_KEYS[kind as SectionKind]]);
  for (const key of Object.keys(raw)) {
    if (!allowed.has(key)) throw new DesignError(`${at}.${key}`, "is not a key this section has");
  }

  const base = { id, kind: kind as SectionKind, ...(hidden ? { hidden: true } : {}) };
  switch (kind as SectionKind) {
    case "hero":
      return {
        ...base,
        kind: "hero",
        heading: text(raw.heading, `${at}.heading`, HEADING_MAX),
        sub: text(raw.sub, `${at}.sub`, SUB_MAX),
        image: imageRef(raw.image, `${at}.image`),
        align: oneOf(raw.align, `${at}.align`, ["start", "center"] as const, "center"),
        height: oneOf(raw.height, `${at}.height`, ["short", "tall"] as const, "short"),
        treatment: oneOf(
          raw.treatment,
          `${at}.treatment`,
          ["panel", "band", "split", "cover"] as const,
          "panel",
        ),
      };
    case "richText":
      return {
        ...base,
        kind: "richText",
        markdown: block(raw.markdown, `${at}.markdown`, MARKDOWN_MAX),
        align: oneOf(raw.align, `${at}.align`, ["start", "center"] as const, "start"),
      };
    case "note":
      return {
        ...base,
        kind: "note",
        note: notePath(raw.note, `${at}.note`),
        heading: text(raw.heading, `${at}.heading`, HEADING_MAX),
        excerpt: bool(raw.excerpt, `${at}.excerpt`, false),
      };
    case "postGrid":
      return {
        ...base,
        kind: "postGrid",
        heading: text(raw.heading, `${at}.heading`, HEADING_MAX),
        limit: int(raw.limit, `${at}.limit`, 1, 48, 6),
        columns: int(raw.columns, `${at}.columns`, 1, 4, 2),
        tag: text(raw.tag, `${at}.tag`, 64),
        showExcerpt: bool(raw.showExcerpt, `${at}.showExcerpt`, true),
        showBanner: bool(raw.showBanner, `${at}.showBanner`, true),
        showDate: bool(raw.showDate, `${at}.showDate`, true),
        card: oneOf(
          raw.card,
          `${at}.card`,
          ["boxed", "bare", "overlay", "ledger", "masonry"] as const,
          "boxed",
        ),
      };
    case "postList":
      return {
        ...base,
        kind: "postList",
        heading: text(raw.heading, `${at}.heading`, HEADING_MAX),
        limit: int(raw.limit, `${at}.limit`, 1, 200, 20),
        tag: text(raw.tag, `${at}.tag`, 64),
        showExcerpt: bool(raw.showExcerpt, `${at}.showExcerpt`, true),
        showDate: bool(raw.showDate, `${at}.showDate`, true),
        layout: oneOf(
          raw.layout,
          `${at}.layout`,
          ["river", "ledger", "index", "numbered", "dateline"] as const,
          "river",
        ),
      };
    case "topics":
      return {
        ...base,
        kind: "topics",
        heading: text(raw.heading, `${at}.heading`, HEADING_MAX),
        limit: int(raw.limit, `${at}.limit`, 1, 60, 12),
      };
    case "cta":
      return {
        ...base,
        kind: "cta",
        heading: text(raw.heading, `${at}.heading`, HEADING_MAX),
        body: text(raw.body, `${at}.body`, SUB_MAX),
        label: text(raw.label, `${at}.label`, 60),
        url: linkRef(raw.url, `${at}.url`),
      };
    case "divider":
      return {
        ...base,
        kind: "divider",
        style: oneOf(
          raw.style,
          `${at}.style`,
          ["rule", "dots", "ornament", "blank"] as const,
          "rule",
        ),
        space: int(raw.space, `${at}.space`, 0, 240, 32),
      };
  }
}

/** The keys each section kind owns — the other half of the strict allowlist.
 *  A key that is not here is a 400 naming it, rather than a value silently
 *  dropped on write and mysteriously absent afterwards. */
const KIND_KEYS: Record<SectionKind, string[]> = {
  hero: ["heading", "sub", "image", "align", "height", "treatment"],
  richText: ["markdown", "align"],
  note: ["note", "heading", "excerpt"],
  postGrid: [
    "heading",
    "limit",
    "columns",
    "tag",
    "showExcerpt",
    "showBanner",
    "showDate",
    "card",
  ],
  postList: ["heading", "limit", "tag", "showExcerpt", "showDate", "layout"],
  topics: ["heading", "limit"],
  cta: ["heading", "body", "label", "url"],
  divider: ["style", "space"],
};

const DOC_KEYS = new Set([
  "id",
  "name",
  "schema",
  "theme",
  "site",
  "chrome",
  "sections",
  "article",
  "createdMs",
  "updatedMs",
]);

/**
 * Validate a whole design document. Throws DesignError (fixable, named) or
 * QuarantineError (this build cannot understand it).
 *
 * `isThemeChoice` is injected rather than imported so this module stays free
 * of the theme list: the CALLER knows which custom themes exist, and a design
 * naming a custom theme that has been deleted must be a named error rather
 * than a silent fallback.
 */
export function validateDesign(
  input: unknown,
  opts: { isThemeChoice?: (value: string) => boolean; now?: number } = {},
): DesignDoc {
  const now = opts.now ?? Date.now();
  const raw = asObject(input, "");

  const declared =
    raw.schema === undefined || raw.schema === null
      ? SCHEMA_UNVERSIONED
      : int(raw.schema, "schema", 0, 9999, SCHEMA_UNVERSIONED);
  const doc = migrateDesign(raw, declared);

  for (const key of Object.keys(doc)) {
    if (!DOC_KEYS.has(key)) throw new DesignError(key, "is not a key a design has");
  }

  const name = text(doc.name, "name", DESIGN_NAME_MAX);
  if (name === "") throw new DesignError("name", "is required");
  const id = typeof doc.id === "string" && SLUG_RE.test(doc.id) ? doc.id : slugifyDesignName(name);

  let theme: string | null = null;
  if (doc.theme !== undefined && doc.theme !== null && doc.theme !== "") {
    const value = text(doc.theme, "theme", 64);
    if (opts.isThemeChoice && !opts.isThemeChoice(value)) {
      throw new DesignError("theme", `names a theme this instance does not have: ${value}`);
    }
    theme = value;
  }

  const siteRaw = doc.site === undefined ? {} : asObject(doc.site, "site");
  const site: DesignSite = {
    width: int(siteRaw.width, "site.width", MIN_WIDTH, MAX_WIDTH, 720),
    density: oneOf(
      siteRaw.density,
      "site.density",
      ["compact", "regular", "roomy"] as const,
      "regular",
    ),
  };
  for (const key of Object.keys(siteRaw)) {
    if (!(key in site)) throw new DesignError(`site.${key}`, "is not a key the site chrome has");
  }

  // The chrome validates itself, in its own module, with the same strictness
  // and the same DesignError — so a hand-edited nav item pointing at
  // `javascript:` is refused here exactly as a malformed section is.
  const chrome = validateChrome(doc.chrome === undefined ? {} : doc.chrome);

  const articleRaw = doc.article === undefined ? {} : asObject(doc.article, "article");
  const article: DesignArticle = {
    showBanner: bool(articleRaw.showBanner, "article.showBanner", true),
    showMeta: bool(articleRaw.showMeta, "article.showMeta", true),
    showTags: bool(articleRaw.showTags, "article.showTags", true),
    showRelated: bool(articleRaw.showRelated, "article.showRelated", true),
    showBackLink: bool(articleRaw.showBackLink, "article.showBackLink", true),
    // Absent means off, which is why this one field defaults the other way to
    // its neighbours: every design authored before the control existed said
    // nothing about it, and "said nothing" must not mean "wanted one".
    dropCap: bool(articleRaw.dropCap, "article.dropCap", false),
  };
  for (const key of Object.keys(articleRaw)) {
    if (!(key in article)) {
      throw new DesignError(`article.${key}`, "is not a key the article page has");
    }
  }

  const rawSections = doc.sections === undefined ? [] : doc.sections;
  if (!Array.isArray(rawSections)) throw new DesignError("sections", "must be an array");
  if (rawSections.length > MAX_SECTIONS) {
    throw new DesignError("sections", `holds too many sections (${MAX_SECTIONS} max)`);
  }
  const seen = new Set<string>();
  const sections = rawSections.map((entry, i) => {
    const section = validateSection(entry, "sections", i);
    // Ids are what the boundary names, so two sections may not share one —
    // a notice pointing at "the hero" when there are two of them is not a
    // notice. Duplicates are renumbered rather than refused: this is the one
    // defect an author cannot cause from the panel and an importer always can.
    let id = section.id;
    for (let n = 2; seen.has(id); n++) id = `${section.id}-${n}`;
    seen.add(id);
    return { ...section, id } as Section;
  });

  const stamp = (value: unknown, fallback: number): number =>
    typeof value === "number" && Number.isFinite(value) && value > 0
      ? Math.floor(value)
      : fallback;

  return {
    id,
    name,
    schema: DESIGN_SCHEMA,
    theme,
    site,
    chrome,
    sections,
    article,
    createdMs: stamp(doc.createdMs, now),
    updatedMs: stamp(doc.updatedMs, now),
  };
}

// ── Migration ───────────────────────────────────────────────────────────────

/** One step up. Keyed by the version being LEFT, so a chain is a fold. */
const MIGRATIONS: Record<number, (doc: Record<string, unknown>) => Record<string, unknown>> = {
  // 0 → 1. "Version 0" is a document with no `schema` key at all: hand-written,
  // produced by an older export, or generated by something else. Nothing in it
  // can be MISunderstood — the fields we do not find, validation supplies — so
  // it migrates rather than quarantining. That is the whole step: stamp the
  // version it is being adopted into, and let the validator fill the rest.
  [SCHEMA_UNVERSIONED]: (doc) => ({ ...doc, schema: 1 }),
};

/**
 * Bring a document up to DESIGN_SCHEMA, or refuse to.
 *
 * Refusing is the important half. A design authored by a NEWER build is
 * quarantined rather than rendered: this build would silently drop the keys it
 * does not know, and "silently drop" is how a public homepage loses a section
 * without anybody being told. An older version with no registered step is the
 * same answer for the same reason. Either way the bytes stay on disk untouched
 * — quarantine is inert, not destructive, and the design comes back the moment
 * a build that understands it runs.
 */
export function migrateDesign(
  doc: Record<string, unknown>,
  declared: number,
): Record<string, unknown> {
  if (declared === DESIGN_SCHEMA) return doc;
  if (declared > DESIGN_SCHEMA) {
    throw new QuarantineError(
      `design schema ${declared} was written by a newer Vellum (this build understands ${DESIGN_SCHEMA}) — kept, not rendered`,
    );
  }
  let current = doc;
  for (let version = declared; version < DESIGN_SCHEMA; version++) {
    const step = Object.prototype.hasOwnProperty.call(MIGRATIONS, version)
      ? MIGRATIONS[version]
      : undefined;
    if (!step) {
      throw new QuarantineError(
        `design schema ${declared} has no migration to ${DESIGN_SCHEMA} — kept, not rendered`,
      );
    }
    current = step(current);
  }
  return current;
}

// ── Export / import ─────────────────────────────────────────────────────────

/** The exported file's shape: the document, plus what produced it. `kind` is
 *  what an importer checks BEFORE parsing, so dropping the wrong JSON on the
 *  panel is a sentence rather than forty field errors. */
export interface DesignExport {
  kind: "vellum.design";
  schema: number;
  exportedAt: string;
  design: DesignDoc;
  /** Custom themes the design references, carried along so a design that
   *  names one arrives complete. Import merges them under fresh ids when they
   *  collide, and NEVER overwrites a theme the receiving instance already has
   *  — an import is an addition, not a merge conflict resolved in silence. */
  themes?: unknown[];
}

export function designExport(design: DesignDoc, themes: unknown[] = []): DesignExport {
  return {
    kind: "vellum.design",
    schema: DESIGN_SCHEMA,
    exportedAt: new Date().toISOString(),
    design,
    ...(themes.length > 0 ? { themes } : {}),
  };
}

/** Pull the document out of an exported file, a bare document, or refuse with
 *  a sentence. Both shapes are accepted on purpose: the file this product
 *  writes, and the object somebody pasted out of it. */
export function readDesignExport(input: unknown): { design: unknown; themes: unknown[] } {
  const raw = asObject(input, "");
  if (raw.kind !== undefined && raw.kind !== "vellum.design") {
    throw new DesignError("kind", "is not a Vellum design file");
  }
  const design = raw.design !== undefined ? raw.design : raw;
  const themes = Array.isArray(raw.themes) ? raw.themes : [];
  return { design, themes };
}
